version: "3"

services:
  keycloak:
    restart: unless-stopped
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    networks:
      - dockerregistry
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: yNCMfkH.1337
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_PROXY: edge
      DB: MYSQL
      DB_URL_HOST: mysql
      DB_SCHEMA: keycloak
      DB_USERNAME: root
      DB_PASSWORD: aplotPWD
    command:
      - start

networks:
  dockerregistry:
    external:
      name: docker-registry_default
