 docker-registry:
    restart: unless-stopped
    container_name: docker-registry
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_STORAGE_DELETE_ENABLED: "yes"
    volumes:
      - data:/var/lib/registry
      - ./auth:/auth

volumes:
  data:
    external: false