version: "3"

services:
  nginx:
    build: .
    restart: unless-stopped
    container_name: nginx
    hostname: nginx
    networks:
      - dockerregistry
      - keycloak
    ports:
      - "80:80"
      - "443:443"
    environment:
      CERTBOT_EMAIL: "a.plotkin@seznam.cz"

networks:
  dockerregistry:
    external:
      name: docker-registry_default
  keycloak:
    external:
      name: keycloak_default
