version: "3"

services:
  mysql:
    restart: unless-stopped
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: aplotPWD
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
    external: false
